package console

const pageTemplate = `{{define "signed_out"}}<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Signed out · cautem Console</title><link rel="stylesheet" href="/assets/console.css"></head><body><main><h1>Signed out</h1><p class="muted">Your console session has ended.</p><p><a href="/login">Sign in</a></p></main></body></html>{{end}}{{define "page"}}<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>cautem Console</title><link rel="stylesheet" href="/assets/console.css"></head><body><header><div><strong>CAUTEM</strong><span class="muted"> / CONTROL</span></div><div class="header-actions"><form method="get" action="/"><select name="workspace" aria-label="Workspace">{{range .Workspaces}}<option value="{{.}}" {{if eq . $.Workspace}}selected{{end}}>{{.}}</option>{{end}}</select><button>Open</button></form><form method="post" action="/logout"><input type="hidden" name="csrf" value="{{.CSRF}}"><button>Sign out</button></form></div></header><main>
<h1>Sandboxes</h1><p class="muted">Gateway-authorized resources in {{.Workspace}}.</p>{{if .Error}}<p class="error">{{.Error}}</p>{{end}}
<section class="metrics"><div class="metric"><span class="muted">Registered</span><strong>{{index .Overview "sandbox_count"}}</strong></div><div class="metric"><span class="muted">Registry running</span><strong>{{index .Overview "registry_running_count"}}</strong></div><div class="metric"><span class="muted">Identity</span><strong class="identity">{{index .Viewer "subject"}}</strong></div></section>
{{if .LifecycleAvailable}}<section class="panel create"><h2>Create sandbox</h2><form method="post" action="/sandboxes/action"><input type="hidden" name="csrf" value="{{.CSRF}}"><input type="hidden" name="workspace" value="{{.Workspace}}"><input type="hidden" name="action" value="create"><label>Name<input required name="name" maxlength="253"></label><label>Image<input required name="image" maxlength="1024" placeholder="ubuntu:24.04"></label><label>Command<input name="command" placeholder="optional command and arguments"></label><button>Create</button></form></section>{{end}}
<section class="grid"><div class="panel"><table><thead><tr><th>Name</th><th>Status</th><th>Image</th><th>Version</th></tr></thead><tbody>{{range .Sandboxes}}<tr><td><a href="/?workspace={{$.Workspace}}&sandbox={{.Name}}">{{.Name}}</a></td><td>{{.Status}}</td><td>{{.Image}}</td><td>{{.ResourceVersion}}</td></tr>{{else}}<tr><td colspan="4" class="muted">No sandboxes</td></tr>{{end}}</tbody></table></div>
<aside class="panel">{{with .Selected}}<h2>{{.Name}}</h2><div class="muted">{{.Workspace}} / {{.ID}}</div><p>Status: {{.Status}}<br>Image: {{.Image}}<br>Version: {{.ResourceVersion}}</p>{{if $.LifecycleAvailable}}<div class="actions">{{if eq .Status "running"}}<form method="post" action="/sandboxes/action"><input type="hidden" name="csrf" value="{{$.CSRF}}"><input type="hidden" name="workspace" value="{{.Workspace}}"><input type="hidden" name="name" value="{{.Name}}"><input type="hidden" name="action" value="stop"><button>Stop</button></form>{{else}}<form method="post" action="/sandboxes/action"><input type="hidden" name="csrf" value="{{$.CSRF}}"><input type="hidden" name="workspace" value="{{.Workspace}}"><input type="hidden" name="name" value="{{.Name}}"><input type="hidden" name="action" value="start"><button>Start</button></form>{{end}}<form method="post" action="/sandboxes/action"><input type="hidden" name="csrf" value="{{$.CSRF}}"><input type="hidden" name="workspace" value="{{.Workspace}}"><input type="hidden" name="name" value="{{.Name}}"><input type="hidden" name="action" value="delete"><label class="confirm"><input type="checkbox" name="confirm" value="delete" required> confirm delete</label><button class="danger">Delete</button></form></div>{{end}}<h2>Recent logs</h2><pre>{{range $.Logs}}{{.TS.Format "15:04:05"}} {{.Level}} {{.Text}}
{{else}}No buffered log lines.{{end}}</pre>{{else}}<p class="muted">Select a sandbox to inspect it.</p>{{end}}</aside></section></main></body></html>{{end}}`

const pageCSS = `:root{color-scheme:dark;--bg:#101512;--panel:#18201b;--line:#34443a;--text:#edf5ef;--muted:#9db0a3;--green:#70e29a;--red:#ff8a80}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px ui-monospace,SFMono-Regular,Menlo,monospace}header,main{max-width:1180px;margin:auto;padding:24px}header,.header-actions,.header-actions form,.actions{display:flex;gap:8px;align-items:center}header{justify-content:space-between;border-bottom:1px solid var(--line)}h1,h2{font-family:system-ui,sans-serif;margin:.2em 0}.muted{color:var(--muted)}select,input,button{background:var(--panel);color:var(--text);border:1px solid var(--line);padding:9px 12px;border-radius:6px}button:hover{border-color:var(--green)}.metrics,.grid{display:grid;gap:16px}.metrics{grid-template-columns:repeat(3,1fr);margin:24px 0}.metric,.panel{background:var(--panel);border:1px solid var(--line);padding:18px;border-radius:8px}.metric strong{display:block;font:32px system-ui,sans-serif}.metric .identity{font-size:18px}.grid{grid-template-columns:2fr 1fr}.create{margin-bottom:16px}.create form{display:grid;grid-template-columns:1fr 2fr 2fr auto;gap:10px;align-items:end}label{display:grid;gap:5px}.confirm{display:flex;align-items:center}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:11px;border-bottom:1px solid var(--line)}a{color:var(--green);text-decoration:none}.actions{margin:14px 0;flex-wrap:wrap}.danger{color:var(--red)}pre{white-space:pre-wrap;max-height:440px;overflow:auto;background:#0a0e0c;padding:12px}.error{color:var(--red)}@media(max-width:800px){.metrics,.grid,.create form{grid-template-columns:1fr}header,.header-actions{align-items:flex-start;flex-direction:column}}`
